### ISSUE TITLE
Which mods it require to install?

### ISSUE THREAD

**Issue by P5ina** [Patbox/IllagerExpansionRecrafted#3]
Hello, I installed trinkets polymer port, polymer, this mod and original trinkets mod, but I'm unable to equip any trinkets gear. Also `/trinkets` doesn't work

**Comment by Patbox** [comment]
Make sure you are in survival (creative is buggy). If you have Trinkets Polymer Port, you don't need original one (and vice versa, they are just alternative implementations of same mods, one for purely server side setups, other for modded ones).
